apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: git.wildberries.ru:4567/oer/go-trainee
  newTag: latest

bases:
- ../../base

resources:
- config.yaml


patchesStrategicMerge:
- resources.yaml
