api_port: "8000"
html_port: "3000"

nats:
  url: "wbx-world-nats-stage.dp.wb.ru, wbx-world-nats-stage.dl.wb.ru"
  subject: "go.test"
  subsc_queue: 'orders_queue'
  opts:
    reconnect_wait_sec: 1
    max_reconnects: 1000

db: 
  host: "develop.wbx-world.vm.prod-3d.cloud.3data"
  port: "5432"
  dbname:   "Orders_test"
  username: "ustelemov_maksim"
  sslmode:  "disable"
  listener:
    min_reconnect_seconds: 10
    max_reconnect_seconds: 60
    ping_noevent_seconds: 90